#pragma once
#include "pch.h"

namespace Axodox::Graphics::D3D12
{
  enum class ComparisonFunction
  {
    Unknown,
    Never = D3D12_COMPARISON_FUNC_NEVER,
    Less = D3D12_COMPARISON_FUNC_LESS,
    Equal = D3D12_COMPARISON_FUNC_EQUAL,
    LessOrEqual = D3D12_COMPARISON_FUNC_LESS_EQUAL,
    Greater = D3D12_COMPARISON_FUNC_GREATER,
    NotEqual = D3D12_COMPARISON_FUNC_NOT_EQUAL,
    GreaterOrEqual = D3D12_COMPARISON_FUNC_GREATER_EQUAL,
    Always = D3D12_COMPARISON_FUNC_ALWAYS
  };

  enum class Format
  {
    Unknown = DXGI_FORMAT_UNKNOWN
  };
  
  enum class PrimitiveTopology
  {
    Undefined = D3D_PRIMITIVE_TOPOLOGY_UNDEFINED,
    PointList = D3D_PRIMITIVE_TOPOLOGY_POINTLIST,
    LineList = D3D_PRIMITIVE_TOPOLOGY_LINELIST,
    LineStrip = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP,
    TriangleList = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
    TriangleStrip = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
    LineListWithAdjacency = D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,
    LineStripWithAdjacency = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,
    TriangleListWithAdjacency = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,
    TriangleStripWithAdjacency = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ,
    PatchList1 = D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST,
    PatchList2 = D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST,
    PatchList3 = D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST,
    PatchList4 = D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST
  };

  enum class ResourceStates
  {
    Common = D3D12_RESOURCE_STATE_COMMON,
    VertexAndConstantBuffer = D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER,
    IndexBuffer = D3D12_RESOURCE_STATE_INDEX_BUFFER,
    RenderTarget = D3D12_RESOURCE_STATE_RENDER_TARGET,
    UnorderedAccess = D3D12_RESOURCE_STATE_UNORDERED_ACCESS,
    DepthWrite = D3D12_RESOURCE_STATE_DEPTH_WRITE,
    DepthRead = D3D12_RESOURCE_STATE_DEPTH_READ,
    NonPixelShaderResource = D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,
    PixelShaderResource = D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,
    StreamOut = D3D12_RESOURCE_STATE_STREAM_OUT,
    IndirectArgument = D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT,
    CopyDest = D3D12_RESOURCE_STATE_COPY_DEST,
    CopySource = D3D12_RESOURCE_STATE_COPY_SOURCE,
    ResolveDest = D3D12_RESOURCE_STATE_RESOLVE_DEST,
    ResolveSource = D3D12_RESOURCE_STATE_RESOLVE_SOURCE,
    RaytracingAccelerationStructure = D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE,
    ShadingRateSource = D3D12_RESOURCE_STATE_SHADING_RATE_SOURCE,
    GenericRead = D3D12_RESOURCE_STATE_GENERIC_READ,
    AllShaderResource = D3D12_RESOURCE_STATE_ALL_SHADER_RESOURCE,
    Present = D3D12_RESOURCE_STATE_PRESENT,
    Predication = D3D12_RESOURCE_STATE_PREDICATION,
    VideoDecodeRead = D3D12_RESOURCE_STATE_VIDEO_DECODE_READ,
    VideoDecodeWrite = D3D12_RESOURCE_STATE_VIDEO_DECODE_WRITE,
    VideoProcessRead = D3D12_RESOURCE_STATE_VIDEO_PROCESS_READ,
    VideoProcessWrite = D3D12_RESOURCE_STATE_VIDEO_PROCESS_WRITE,
    VideoEncodeRead = D3D12_RESOURCE_STATE_VIDEO_ENCODE_READ,
    VideoEncodeWrite = D3D12_RESOURCE_STATE_VIDEO_ENCODE_WRITE
  };
}