#pragma once
#include "pch.h"

namespace Axodox::Graphics
{
  enum class ComparisonFunction
  {
    Unknown,
    Never = D3D12_COMPARISON_FUNC_NEVER,
    Less = D3D12_COMPARISON_FUNC_LESS,
    Equal = D3D12_COMPARISON_FUNC_EQUAL,
    LessOrEqual = D3D12_COMPARISON_FUNC_LESS_EQUAL,
    Greater = D3D12_COMPARISON_FUNC_GREATER,
    NotEqual = D3D12_COMPARISON_FUNC_NOT_EQUAL,
    GreaterOrEqual = D3D12_COMPARISON_FUNC_GREATER_EQUAL,
    Always = D3D12_COMPARISON_FUNC_ALWAYS
  };

  enum class Format
  {
    Unknown = DXGI_FORMAT_UNKNOWN
  };
  
  enum class PrimitiveTopology
  {
    Undefined = D3D_PRIMITIVE_TOPOLOGY_UNDEFINED,
    PointList = D3D_PRIMITIVE_TOPOLOGY_POINTLIST,
    LineList = D3D_PRIMITIVE_TOPOLOGY_LINELIST,
    LineStrip = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP,
    TriangleList = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
    TriangleStrip = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
    LineListWithAdjacency = D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,
    LineStripWithAdjacency = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,
    TriangleListWithAdjacency = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,
    TriangleStripWithAdjacency = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ,
    PatchList1 = D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST,
    PatchList2 = D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST,
    PatchList3 = D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST,
    PatchList4 = D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST
  };
}