#pragma once
#include "../includes.h"

#include "Graphics/DirectX12/Enumerations.h"
#include "Graphics/DirectX12/GraphicsTypes.h"
#include "Graphics/DirectX12/Devices/GraphicsDevice.h"
#include "Graphics/DirectX12/Commands/CommandQueue.h"
#include "Graphics/DirectX12/Commands/CommandFence.h"
#include "Graphics/DirectX12/Commands/CommandList.h"
#include "Graphics/DirectX12/Commands/CommandAllocator.h"
#include "Graphics/DirectX12/Swap Chains/SwapChain.h"
#include "Graphics/DirectX12/Swap Chains/CoreSwapChain.h"
#include "Graphics/DirectX12/States/RootParameters.h"
#include "Graphics/DirectX12/States/StaticSampler.h"
#include "Graphics/DirectX12/States/RootSignature.h"
#include "Graphics/DirectX12/States/PipelineState.h"
#include "Graphics/DirectX12/Resources/DynamicBufferManager.h"
#include "Graphics/DirectX12/Resources/CommittedResourceAllocator.h"
#include "Graphics/DirectX12/Resources/GroupedResourceAllocator.h"
#include "Graphics/DirectX12/Resources/ResourceUploader.h"
#include "Graphics/DirectX12/Resources/ImmutableTexture.h"
#include "Graphics/DirectX12/Meshes/VertexDefinitions.h"
#include "Graphics/DirectX12/Meshes/MeshDescriptions.h"
#include "Graphics/DirectX12/Meshes/Primitives.h"
#include "Graphics/DirectX12/Meshes/Mesh.h"
#include "Graphics/DirectX12/Descriptors/Descriptor.h"
#include "Graphics/DirectX12/Descriptors/DescriptorHeap.h"
#include "Graphics/DirectX12/Descriptors/RenderTargetView.h"
#include "Graphics/DirectX12/Descriptors/DepthStencilView.h"
#include "Graphics/DirectX12/Descriptors/ConstantBufferView.h"
#include "Graphics/DirectX12/Descriptors/ShaderResourceView.h"
#include "Graphics/DirectX12/Descriptors/CommonDescriptorHeap.h"